services:
  db:
    image: postgres
    container_name: trackion_db
    restart: always
    environment:
      POSTGRES_USER: trackion
      POSTGRES_PASSWORD: trackion
      POSTGRES_DB: trackion_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
